<html>
    <head>
        <title>Error-try, catch, finally</title>
    </head>
    <body>
        <script>
            // consol.log("안녕하세요");
            // console.log("오늘은 즐거운 금요일입니다");

            try{
                consol.log("안녕하세요");
            }catch(error){
                console.log(error.name);
                console.log(error.message);
            }
            console.log("오늘은 즐거운 금요일입니다");

            //throw를 사용하여 강제로 Exception 발생
            var x = "";
            try {
                if(x === "") throw "Empty";
                var y = x + 3;
                console.log(y);
            } catch (error) {
                console.log(`x is ${error}`);
            }

            finally{
                console.log("에러 유무와 상관없이 무조건 실행");
            }
        </script>
    </body>
</html>